### ISSUE TITLE
All Colors disappeared

### ISSUE THREAD

**Issue by lewisou** [fphilipe/premailer-rails#118]
Why in the html of mail, I only get black and white for font as well as the background. By looking at the html sourcecode, I saw background-color:transparent!important has been added everywhere.

Any idea?

btw, the color was there before I upgraded the ruby version from 1.9 to 2.1. And I also removed rvm to use rbenv at the same time. I was using premailer-rails3 previously, which seems having same problem after upgrading the ruby version. (now I am using permailer-rails, and still having the same color issue.)

**Comment by Basemasta** [comment]
I think i'm facing the same issue.
Looking at the code, my best bet is that the attributs come from [boostrap.css](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css) `@media print` :
```css
@media print {
  *,
  *:before,
  *:after {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    -webkit-box-shadow: none !important;
            box-shadow: none !important;
  }
…
}
```
All of those attributs are applied to all HTML elements.
This may be related to https://github.com/premailer/premailer/issues/242
