### ISSUE TITLE
CSS rendered differently in production and development mode

### ISSUE THREAD

**Issue by abhayathapa** [fphilipe/premailer-rails#58]
When I send emails in development mode, the css is rendered perfectly in gmail.But, when I send the same email in production mode, the CSS gets broken in couple of places. I even tried `rake:assets:precompile` before sending the email. Stylesheet has been included in the HEAD section of mailer as `<%= stylesheet_link_tag 'email/my_css' %>` Is it a problem with a premailer or something that is to be configuerd for production mode. Am I missing something ?

**Comment by fahmiardhianto** [comment]
So I use this gem for quite a while now and I have some issue that related. In email that I sent, I included image and sets its height in scss file. In development, everything great, image rendered with correct height. But in production, I can't get it right. I try resetting the app, the background job. I can't pinpoint the issue. Any suggestion?

**Comment by fphilipe** [comment]
Hard to understand without code. Mind showing some?

**Comment by fahmiardhianto** [comment]
I have this image inside my email html
```html
<div class="header">
    <%= image_tag 'logo-light.png', height: '45' %>
</div>
```

Here's the style for those element
```css
table.body-wrap .container .header{
  margin-bottom:10px;
  background: #1C788E;
  height: 75px;
  width:100%;
  border-radius: 1px;
}

table.body-wrap .container .header img{
  height: 45px;
  vertical-align: middle;
  padding: 15px 0;

  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}
```

This is the rendered element in development using mailer preview
```html
<img height="45" src="//localhost:3000/assets/logo-light-753ab2cd9b99ecc1d3b24005fba3f3aa1e85a5e5e5b1820fd93a336d12702d93.png" alt="Logo light" style="border-top-left-radius: 5px; border-top-right-radius: 5px; color: #fff; font-family: 'Bariol', 'Open Sans','Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; height: 45px; line-height: 1.5em; margin: 0; padding: 15px 0; text-align: center; vertical-align: middle">
```

And this is rendered element in production
```html
<img src="https://ci5.googleusercontent.com/proxy/zqB3SKzsMQPGmc0MPF3jUby1LidTw5hkNhxpaqSuxXeO8ejHtHrbIivJoZZGYxCEYuTI_gYXXRbFN2rsv78w6DizJyVqCm38nOdlrTLWxa5an4GDgACzY8aTFJbKJF_PXs6LgMevH7WhlCNFjqHOdvfQN4gFrDEVRt2LMQQKx9yY=s0-d-e1-ft#https://www.handl.in/assets/logo-light-753ab2cd9b99ecc1d3b24005fba3f3aa1e85a5e5e5b1820fd93a336d12702d93.png" alt="Logo light" style="border-top-left-radius:5px;border-top-right-radius:5px;color:#fff;font-family:'Bariol','Open Sans','Helvetica Neue','Helvetica',Helvetica,Arial,sans-serif;font-size:100%;min-height:45px;line-height:1.5em;margin:0;padding:15px 0;text-align:center;vertical-align:middle">
```

The difference between the rendered element in development and production is the height. In dev, the height properly set to 45px, but in production somehow the style become `min-height:45px;`. Notice that in the image_tag code I gave the height property but still no luck.
